[project]
name = "gitui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
    "pyvis>=0.3.2",
    "structlog>=25.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
]
